Contact form
Enekwestanley/Portifolio-page pull request #3
Opened 2022-03-22 21:27 UTC by Enekwestanley

This is project to add the contact section of the Portfolio Page.

Technologies used;

- Github
- Vs code

Built with;

- HTML
- CSS

2022-03-22 21:32 UTC, rotimiazeez reviewed
# Hi Team, 

### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that That's not passing the linter checks. Kindly fix this and submit it again.💪🏽

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-03-22 23:36 UTC, medaminedev66 requested changes
Hi @aimalamiri and @Enekwestanley 😃, :wave:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- ✔️The repo looks professional
- ✔️Git/GitHub flow best practices have been followed
- ✔️There are no linter errors


## Required Changes ♻️

_See the inline comments below for more required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 23:36 UTC, medaminedev66 commented on index.html
> +          <input  id="name" type="text" required placeholder="Enter your Name">
- [ ] As stated in the project requirements: Please ensure that the name input accepts up to 30 chars. You can do this by adding the `maxlength="30"` attribute.

2022-03-22 23:36 UTC, medaminedev66 commented on index.html
> +          <textarea name="message" id="message" cols="30" rows="10" required placeholder="Write your messge here"></textarea>
- [ ] Message input also should have `maxlength="500"` attribute.

2022-03-22 23:36 UTC, medaminedev66 commented on index.html
> +          <button type="submit" class="touch">Get in Touch</button>
- [ ] Your form button design is great 👍. Can you please also follow the button styling: Active, Hover, and Pressed (see Figma design below). This makes your User Experience better.
<img width="445" alt="image" src="https://user-images.githubusercontent.com/77190203/159593366-d2fe7d79-302b-49d2-acf1-807b0b1369d0.png">

2022-03-23 00:32 UTC, BenMukebo approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @Enekwestanley ** , 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Your Design looks awesome, keep rocking :rocket: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 08:26 UTC, merged